[package]
name = "vectorchord-indexing"
version = "0.1.0"
edition = "2021"

[features]
default = []


[dependencies]
faiss = { workspace = true }
faiss-sys = { workspace = true }
log = "0.4.28"
pgrx = { workspace = true }
