[package]
name = "vectorchord-indexing"
version = "0.1.0"
edition = "2021"

[features]
default = []


[dependencies]
cuvs = { workspace = true }
ndarray = { workspace = true }
pgrx = { workspace = true }
